"""empty message

Revision ID: 06513c6ce973
Revises: 9db324456e22
Create Date: 2020-02-05 19:33:54.142457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06513c6ce973'
down_revision = '9db324456e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
